name: Keep GraphQL Alive
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  GraphQL-Keep-Awke:
    runs-on: curlimages/curl
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "Hitting the graphql endpoint"
      - run: curl -X POST https://www.prescottjr.com/api/graphql
